env:
  global:
    - CI_NAME=travis-pro
    - COVERALLS_REPO_TOKEN= GE19xAZlricEetWKcSND3It5iKWy8Uk3P


language: java
jdk:
  - oraclejdk8          // tells Travis to use Java 8

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
  
